Repository MonicaGuimaraes/burger-queen-api-client, pull requests merged in 2022-06, with the labels that each got.

#9 Adicionando o carrinho na pagina do Menu.(#3)
  src/API/CreateOrder.js
  src/API/LoginAPI.js
  src/API/MenuAPI.js
  src/assets/Home.svg
  src/assets/Vector.svg
  src/assets/trash.svg
  src/components/buttonHome/ButtonHome.module.css
  src/components/buttonHome/index.jsx
  src/components/buttons/index.jsx
  src/components/buttonsNavigate/buttonNav.module.css
  src/components/buttonsNavigate/index.jsx
  src/components/cart/Cart.module.css
  src/components/cart/index.jsx
  src/components/functions/manipulatingArray.js
  src/components/functions/standardizeName.js
  src/components/handlingErrors/index.jsx
  src/components/products/Products.module.css
  src/components/products/index.jsx
  src/components/productsCart/ProductsCart.module.css
  src/components/productsCart/index.jsx
  src/pages/home/Home.module.css
  src/pages/home/index.js
  src/pages/login/Login.test.js
  src/pages/login/index.js
  src/pages/menu/Menu.module.css
  src/pages/menu/index.js
  src/pages/register/index.js
  src/reset.css
Labels: Feat

#17 Tests/issue3/4
  src/API/CreateOrder.js
  src/App.js
  src/components/buttonHome/buttonHome.test.js
  src/components/buttons/buttons.test.js
  src/components/buttonsNavigate/buttonNavigate.test.js
  src/components/buttonsNavigate/index.jsx
  src/components/cart/cart.test.js
  src/components/cart/index.jsx
  src/components/command/command.test.js
  src/components/command/index.jsx
  src/components/containerOrder/index.jsx
  src/components/functions/closeAndOpen.js
  src/components/functions/statusOrder.js
  src/components/functions/tempCommand.test.js
  src/components/handlingResponseAPI/HandlingResponseAPI.module.css
  src/components/handlingResponseAPI/handlingResponseAPI.test.js
  src/components/handlingResponseAPI/index.jsx
  src/components/inputs/inputs.test.js
  src/components/productsCart/productsCart.test.js
  src/pages/home/index.js
  src/pages/login/Login.test.js
  src/pages/login/index.js
  src/pages/menu/index.js
  src/pages/menu/menu.test.js
  src/pages/order/index.js
  src/pages/order/order.test.js
  src/pages/orderFinalized/index.js
  src/pages/register/index.js
Labels: bug, Feat

#18 Testes de componentes
  src/components/cart/cart.test.js
  src/components/cart/index.jsx
  src/components/containerOrder/containerOrder.test.js
  src/components/containerOrder/index.jsx
  src/components/handlingResponseAPI/handlingResponseAPI.test.js
  src/components/handlingResponseAPI/index.jsx
  src/components/inputs/inputs.test.js
  src/pages/login/Login.test.js
  src/pages/login/index.js
  src/pages/menu/menu.test.js
  src/pages/register/index.js
  src/pages/register/register.test.js
Labels: Feat

#19 Doc: Adicionando o ReadMe.
  README.md
  src/API/DeleteOrders.js
  src/components/buttonHome/ButtonHome.module.css
  src/components/buttons/ButtonSubmit.module.css
  src/components/cart/Cart.module.css
  src/components/cart/index.jsx
  src/reset.css
Labels: documentation

#23 fix:Arrumando o Read.me
  .vscode/settings.json
  README.md
  package.json
  src/API/ChangeStatusAPI.js
  src/pages/order/order.test.js
Labels: documentation
